/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package coba;

/**
 *
 * @author Limun
 */
public class Transaksi2 extends javax.swing.JFrame {

    /**
     * Creates new form Transaksi2
     */
    public Transaksi2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CustomerList = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ProductList = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        Transaksi = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        NameMember = new javax.swing.JLabel();
        inputNamamember = new javax.swing.JTextField();
        EmailMember = new javax.swing.JLabel();
        inputEmail = new javax.swing.JTextField();
        NoHP = new javax.swing.JLabel();
        inputNohp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        NameMember1 = new javax.swing.JLabel();
        inputNamaproduk = new javax.swing.JTextField();
        inputHarga = new javax.swing.JTextField();
        EmailMember1 = new javax.swing.JLabel();
        inputDeskripsi = new javax.swing.JTextField();
        NoHP1 = new javax.swing.JLabel();
        EmailMember2 = new javax.swing.JLabel();
        inputJumlah = new javax.swing.JTextField();
        tambahTroli = new javax.swing.JButton();
        labeltotalharga = new javax.swing.JLabel();
        jumlahHarga = new javax.swing.JLabel();
        tambahTroli1 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel1.setText("Manage Order");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 19, -1, -1));

        CustomerList.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CustomerList.setText("Customer List");
        getContentPane().add(CustomerList, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 86, -1, -1));

        jTable1.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama", "Email", "No HP", "Domisili"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(20);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(25);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 110, 287, 238));

        ProductList.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ProductList.setText("Product List");
        getContentPane().add(ProductList, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 86, -1, -1));

        jTable2.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kode", "Nama", "QTY", "Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setMaxWidth(35);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 110, 262, 238));

        Transaksi.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        Transaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Kode Produk", "Nama", "QTY", "Deskripsi", "Diskon", "Sub Total"
            }
        ));
        jScrollPane3.setViewportView(Transaksi);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(567, 110, 380, 238));

        jLabel2.setText("Selected Customer");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 366, -1, -1));

        NameMember.setText("Name");
        getContentPane().add(NameMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));
        getContentPane().add(inputNamamember, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 422, 152, -1));

        EmailMember.setText("Email");
        getContentPane().add(EmailMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 456, -1, -1));
        getContentPane().add(inputEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 478, 152, -1));

        NoHP.setText("No HP");
        getContentPane().add(NoHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 518, -1, -1));
        getContentPane().add(inputNohp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 152, -1));

        jLabel3.setText("Selected Product");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 366, -1, -1));

        NameMember1.setText("Nama Produk");
        getContentPane().add(NameMember1, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 400, -1, -1));
        getContentPane().add(inputNamaproduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 422, 224, -1));
        getContentPane().add(inputHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 596, 224, -1));

        EmailMember1.setText("Harga");
        getContentPane().add(EmailMember1, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 574, -1, -1));
        getContentPane().add(inputDeskripsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 540, 224, -1));

        NoHP1.setText("Deskripsi");
        getContentPane().add(NoHP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 518, -1, -1));

        EmailMember2.setText("Jumlah");
        getContentPane().add(EmailMember2, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 462, -1, -1));
        getContentPane().add(inputJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 484, 224, -1));

        tambahTroli.setText("Tambahkan Troli");
        getContentPane().add(tambahTroli, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 636, 224, -1));

        labeltotalharga.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labeltotalharga.setText("Total Harga : Rp.");
        getContentPane().add(labeltotalharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 386, -1, -1));

        jumlahHarga.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jumlahHarga.setText("0000");
        getContentPane().add(jumlahHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(766, 386, -1, -1));

        tambahTroli1.setText("Simpan Transaksi");
        getContentPane().add(tambahTroli1, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 415, 224, -1));

        background.setForeground(new java.awt.Color(204, 255, 0));
        background.setText("jLabel4");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaksi2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaksi2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaksi2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaksi2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaksi2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CustomerList;
    private javax.swing.JLabel EmailMember;
    private javax.swing.JLabel EmailMember1;
    private javax.swing.JLabel EmailMember2;
    private javax.swing.JLabel NameMember;
    private javax.swing.JLabel NameMember1;
    private javax.swing.JLabel NoHP;
    private javax.swing.JLabel NoHP1;
    private javax.swing.JLabel ProductList;
    private javax.swing.JTable Transaksi;
    private javax.swing.JLabel background;
    private javax.swing.JTextField inputDeskripsi;
    private javax.swing.JTextField inputEmail;
    private javax.swing.JTextField inputHarga;
    private javax.swing.JTextField inputJumlah;
    private javax.swing.JTextField inputNamamember;
    private javax.swing.JTextField inputNamaproduk;
    private javax.swing.JTextField inputNohp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel jumlahHarga;
    private javax.swing.JLabel labeltotalharga;
    private javax.swing.JButton tambahTroli;
    private javax.swing.JButton tambahTroli1;
    // End of variables declaration//GEN-END:variables
}
